name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go: [ 1.18.x, 1.19.x, 1.20.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Go ${{ matrix.go }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go ${{ matrix.go }} on ${{ matrix.os }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        cache: true

    - name: Test
      run: go test ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.txt