on:
  pull_request:
  push:
    branches:
      - master
name: Test
jobs:
  test:
    strategy:
      matrix:
        go: [ 1.18.x, 1.19.x, 1.20.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Go ${{ matrix.go }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        cache: true
    - run: go test ./...